/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Facebook.java
 *
 * Created on Nov 12, 2013, 11:09:30 AM
 */

/**
 *
 * @author HCL2
 */

import java.sql.*;
import javax.swing.*;
public class Facebook extends javax.swing.JFrame {

    /** Creates new form Facebook */
    public Facebook() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        jb = new javax.swing.JButton();
        jd2 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jb2 = new javax.swing.JButton();
        profileframe = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        propic = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        chatList = new javax.swing.JList();
        chatlabel = new javax.swing.JLabel();
        chatlist = new javax.swing.JButton();
        cb = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusarea = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        stsa1 = new javax.swing.JTextArea();
        stsl1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        stsa2 = new javax.swing.JTextArea();
        stsl2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        stsa3 = new javax.swing.JTextArea();
        stsl3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        delchat = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        chatline = new javax.swing.JTextArea();
        chatbut = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        chatbox = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        t2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t6 = new javax.swing.JPasswordField();
        t7 = new javax.swing.JTextField();
        jcb1 = new javax.swing.JComboBox();
        jcb2 = new javax.swing.JComboBox();
        jcb3 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jd1.setMinimumSize(new java.awt.Dimension(599, 165));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(265, 140));

        l1.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));

        jb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fh.PNG"))); // NOI18N
        jb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jb, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jb, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jd1Layout = new javax.swing.GroupLayout(jd1.getContentPane());
        jd1.getContentPane().setLayout(jd1Layout);
        jd1Layout.setHorizontalGroup(
            jd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jd1Layout.setVerticalGroup(
            jd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jd2.setMinimumSize(new java.awt.Dimension(750, 480));

        jPanel3.setBackground(new java.awt.Color(51, 255, 51));

        jb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc.png"))); // NOI18N
        jb2.setBorder(null);
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jb2)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jb2)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd2Layout = new javax.swing.GroupLayout(jd2.getContentPane());
        jd2.getContentPane().setLayout(jd2Layout);
        jd2Layout.setHorizontalGroup(
            jd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd2Layout.setVerticalGroup(
            jd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        profileframe.setBounds(new java.awt.Rectangle(0, 0, 980, 710));
        profileframe.setResizable(false);
        profileframe.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                profileframeWindowActivated(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(1035, 845));

        propic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/propicdef.png"))); // NOI18N
        propic.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        l3.setFont(new java.awt.Font("Lucida Handwriting", 3, 24)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("Welcome  ");

        chatList.setBackground(new java.awt.Color(51, 153, 255));
        chatList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.SystemColor.activeCaption, null, java.awt.Color.white));
        chatList.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        chatList.setForeground(new java.awt.Color(255, 255, 255));
        chatList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "fgjk", "fdhg", "gfhjgj" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        chatList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(chatList);

        chatlabel.setFont(new java.awt.Font("Lucida Handwriting", 3, 15)); // NOI18N
        chatlabel.setForeground(new java.awt.Color(255, 255, 255));

        chatlist.setText("dont del me ");
        chatlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatlistActionPerformed(evt);
            }
        });

        cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel6.setBackground(new java.awt.Color(51, 153, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        statusarea.setColumns(20);
        statusarea.setLineWrap(true);
        statusarea.setRows(5);
        jScrollPane1.setViewportView(statusarea);

        jButton4.setText("share");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4))
        );

        jPanel7.setBackground(new java.awt.Color(51, 153, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jPanel8.setBackground(new java.awt.Color(51, 153, 255));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        stsa1.setColumns(20);
        stsa1.setEditable(false);
        stsa1.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        stsa1.setLineWrap(true);
        stsa1.setRows(5);
        jScrollPane5.setViewportView(stsa1);

        stsl1.setFont(new java.awt.Font("Lucida Calligraphy", 3, 15)); // NOI18N
        stsl1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(stsl1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(stsl1, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.setBackground(new java.awt.Color(51, 153, 255));
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        stsa2.setColumns(20);
        stsa2.setEditable(false);
        stsa2.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        stsa2.setLineWrap(true);
        stsa2.setRows(5);
        jScrollPane6.setViewportView(stsa2);

        stsl2.setFont(new java.awt.Font("Lucida Calligraphy", 3, 15)); // NOI18N
        stsl2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(stsl2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(stsl2, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel10.setBackground(new java.awt.Color(51, 153, 255));
        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        stsa3.setColumns(20);
        stsa3.setEditable(false);
        stsa3.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        stsa3.setLineWrap(true);
        stsa3.setRows(5);
        jScrollPane7.setViewportView(stsa3);

        stsl3.setFont(new java.awt.Font("Lucida Calligraphy", 3, 15)); // NOI18N
        stsl3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(stsl3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(stsl3, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton5.setText("log out ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        delchat.setText("del chat");
        delchat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delchatActionPerformed(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(51, 153, 255));

        chatline.setColumns(20);
        chatline.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        chatline.setLineWrap(true);
        chatline.setRows(5);
        chatline.setText(" ");
        jScrollPane4.setViewportView(chatline);

        chatbut.setText("OK");
        chatbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatbutActionPerformed(evt);
            }
        });

        chatbox.setColumns(18);
        chatbox.setEditable(false);
        chatbox.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        chatbox.setLineWrap(true);
        chatbox.setRows(5);
        chatbox.setBorder(null);
        chatbox.setMaximumSize(new java.awt.Dimension(10, 23));
        jScrollPane3.setViewportView(chatbox);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane4, 0, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chatbut, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chatbut, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(chatlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(delchat)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(propic, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l3, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chatlist, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propic)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chatlist)
                                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton5))
                        .addGap(123, 123, 123)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(delchat)
                                    .addComponent(chatlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout profileframeLayout = new javax.swing.GroupLayout(profileframe.getContentPane());
        profileframe.getContentPane().setLayout(profileframeLayout);
        profileframeLayout.setHorizontalGroup(
            profileframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        profileframeLayout.setVerticalGroup(
            profileframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setBounds(new java.awt.Rectangle(500, 200, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));
        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 46)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("facebook ");

        t1.setNextFocusableComponent(t2);
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 2, 14)); // NOI18N
        jLabel2.setText("user name ");

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 2, 14)); // NOI18N
        jLabel3.setText("password ");

        jButton3.setText("Asli Log In ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sign Up ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Handwriting", 3, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 2, 14)); // NOI18N
        jLabel4.setText("user ");

        jLabel5.setFont(new java.awt.Font("Lucida Handwriting", 2, 14)); // NOI18N
        jLabel5.setText("email id ");

        jLabel6.setFont(new java.awt.Font("Lucida Handwriting", 2, 14)); // NOI18N
        jLabel6.setText("password ");

        jLabel7.setFont(new java.awt.Font("Lucida Handwriting", 2, 14)); // NOI18N
        jLabel7.setText("date of birth ");

        t3.setText("First Name");
        t3.setToolTipText("");
        t3.setNextFocusableComponent(t2);
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });

        t4.setNextFocusableComponent(t2);
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });

        t7.setText("Last Name ");
        t7.setNextFocusableComponent(t2);
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });

        jcb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jcb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec" }));

        jcb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960" }));

        jButton2.setText("Sign up ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        l2.setFont(new java.awt.Font("Lucida Handwriting", 2, 22)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(45, 45, 45)
                                .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t4, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(32, 32, 32)
                                .addComponent(t6, 0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t7, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l2, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t2, 0, 1, Short.MAX_VALUE)
                            .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Database");

        jMenuItem1.setText("create database");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 String user="";
       String password="";
String id="",pwrd="",fname="";int one=1;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

      user=t1.getText();
       password=t2.getText();
       String temp="";
       if(user.equals("")){
       temp="user"; l1.setText("22 G "+temp+" ta bharo ");jd1.setVisible(true);
       }
       else if(password.equals("")){
       temp="password";l1.setText("22 G "+temp+" ta bharo ");jd1.setVisible(true);
       }

       else{
       int len=user.length();
       int one=0;
       for(int i=0; i<len;i++){
       if(user.charAt(i)=='@'){one=1;}}

       if(one==0){l1.setText("22 G User ta Sahi Bhar lo "); jd1.setVisible(true); }
       else{
       l1.setText("Chotu eda v kdi Facebook chaldi. BABA G DA THULLU LAI HUN ");jd1.setMinimumSize(new java.awt.Dimension(599, 400));jb.setVisible(true); jd1.setVisible(true);
   }



       }







        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void jbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActionPerformed

        jb2.setVisible(true); jd2.setVisible(true);jb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abc.png")));  // TODO add your handling code here:
    }//GEN-LAST:event_jbActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed






// TODO add your handling code here:
}//GEN-LAST:event_jb2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed



 user=t1.getText();
       password=t2.getText();
       String temp="";
       if(user.equals("")){
       temp="user"; JOptionPane.showMessageDialog(null, "22 G "+temp+" ta bharo ");       }
       else if(password.equals("")){
       temp="password"; JOptionPane.showMessageDialog(null, "22 G "+temp+" ta bharo ");
       }

 
  
       else{
       jb.setVisible(false); jd1.setVisible(false);
   



        try{
            
            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/facebook","root","");
            Statement stmt=con.createStatement();
            String query="Select * from profile;";
            ResultSet rs=stmt.executeQuery(query);
           String x="";
            while(rs.next()&&one==1){
                 id=rs.getString("id");
                pwrd=rs.getString("pwrd");
              fname=rs.getString("fname");
             x=login();

            }
if(x.equals("no")){

JOptionPane.showMessageDialog(null, "ID or PASSWORD is wrong.");

}
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

       }

    
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed



public String login(){
String x="";

 if(id.equalsIgnoreCase(user)&&pwrd.equals(password)){
one=0;
profileframe.setVisible(true);



 l3.setText("Welcome "+fname);
 statusarea.setText("");
chatbox.setText("");
chatline.setText("");
chatlabel.setText("");
t1.setText("");
t2.setText("");
}
 else{
 x="no";}
return x;

}


    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed
int wrongid=0;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

l2.setText(""); wrongid=0;

        String newEID=t4.getText().toLowerCase();
        String fname=t3.getText(),lname=t7.getText(),pwrd=t6.getText();
        String date=""+jcb1.getSelectedItem(),month=""+(jcb2.getSelectedIndex()+1),year=""+jcb3.getSelectedItem();
        String dob=""+year+"-"+month+"-"+date;

        

if(newEID.equals(null)||fname.equals("")||pwrd.equals("")){
l2.setText("22 g dvara check kro ");}


        
else{
        try{

            Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/facebook","root","");
            Statement stmt=con.createStatement();
            String query="Select id from profile;";
            ResultSet rs=stmt.executeQuery(query);

            while(rs.next()){
                 id=rs.getString("id");
                 if(id.equalsIgnoreCase(newEID)){
                l2.setText("22 g id glt a"); t4.setText(""); wrongid=1;}}


if(wrongid==0){

        query="insert into profile values ('"+newEID+"','"+pwrd+"','"+fname+"','"+lname+"','"+dob+"');";
stmt.executeUpdate(query);
t4.setText("");
t6.setText("");
t3.setText("First Name");
t7.setText("Last Name");
jcb1.setSelectedIndex(0);
jcb2.setSelectedIndex(0);
jcb3.setSelectedIndex(0);
JOptionPane.showMessageDialog(this, "22 G id bn gyi a upron log in kro");
}


        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }


}






        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
int j=0;
    private void chatbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatbutActionPerformed

        String listid=(String)chatList.getSelectedValue();
chatlabel.setText(listid);

 Connection con;
        Statement stmt;
        ResultSet rs;

chatbox.setVisible(true);
chatline.setVisible(true);
chatbut.setVisible(true);
String old_chat="",new_line="";


   try{

            Class.forName("java.sql.DriverManager");
 con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/facebook","root","");
 stmt=(Statement) con.createStatement();




  rs=stmt.executeQuery("select chat  from chat  where id_to='"+id+"'and id_from='"+listid+"';");


        while(rs.next()){
           old_chat=rs.getString("chat");

}


new_line=chatline.getText();
chatline.setText("");
if(!new_line.equals("")){
old_chat="\n"+old_chat+id+"> "+new_line+"\n-------------------------";
}
else{
old_chat=old_chat+new_line;
}



  stmt.executeUpdate("delete from chat  where id_to='"+listid+"' and id_from='"+id+"';");
  stmt.executeUpdate("delete from chat  where id_to='"+id+"' and id_from='"+listid+"';");
stmt.executeUpdate("insert into chat values('"+listid+"','"+id+"','"+old_chat+"');");
stmt.executeUpdate("insert into chat values('"+id+"','"+listid+"','"+old_chat+"');");


 rs=stmt.executeQuery("select chat from chat  where id_to='"+listid+"' and id_from='"+id+"';");

 
        while(rs.next()){
 old_chat=rs.getString("chat");

}

chatbox.setText("");
chatbox.setText(old_chat);

old_chat="";
new_line="";


         }
catch(Exception e){
JOptionPane.showConfirmDialog(null, e.getMessage());

}



        // TODO add your handling code here:
}//GEN-LAST:event_chatbutActionPerformed

    private void chatlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatlistActionPerformed
chatbox.setVisible(false);
chatline.setVisible(false);
chatbut.setVisible(false);
        cb.setVisible(false);
chatlist.setVisible(false);

        Connection con;
        Statement stmt;
        ResultSet rs;
        DefaultComboBoxModel lm;
        int need=0;


         lm=(DefaultComboBoxModel)cb.getModel();
  lm.removeAllElements(); 



   try{

            Class.forName("java.sql.DriverManager");
 con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/facebook","root","");
 stmt=(Statement) con.createStatement();
  rs=stmt.executeQuery("select id from profile where id !='"+id+"';");
while(rs.next()){
String id_to=rs.getString("id");


lm.addElement(id_to);


}chatList.setModel(lm);

int i=0;
delchat.setVisible(false);
stmt.executeUpdate("delete from status where day(time)<day(sysdate()-7);");
 rs=stmt.executeQuery("select * from status order by time desc;");
while(rs.next()&&i<3){
i++;

if(i==1){
stsl1.setText(" "+rs.getString("id")+"  >");
stsa1.setText(rs.getString("sts")+"\n                                                        "+rs.getString("time"));
}

if(i==2){
stsl2.setText(" "+rs.getString("id")+"  >");
stsa2.setText(rs.getString("sts")+"\n                                                       "+rs.getString("time"));
}

if(i==3){
stsl3.setText(" "+rs.getString("id")+"  >");
stsa3.setText(rs.getString("sts")+"\n                                                       "+rs.getString("time"));
}




}





        }
catch(Exception e){
JOptionPane.showConfirmDialog(null, e.getMessage());

}





        // TODO add your handling code here:
}//GEN-LAST:event_chatlistActionPerformed

    private void profileframeWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_profileframeWindowActivated
chatlist.doClick();





// TODO add your handling code here:
    }//GEN-LAST:event_profileframeWindowActivated
int ok=0;
    private void chatListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatListMouseClicked

        chatbox.setText("");
        chatline.setText("");


        ok=0;
        chatbut.doClick();delchat.setVisible(true);



// TODO add your handling code here:
    }//GEN-LAST:event_chatListMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 String sts="",stsid="",time="";
        sts=statusarea.getText();
       

       if(sts.equals("")){
        JOptionPane.showMessageDialog(this,"22 G tu c kuj likheya e nhi :P "); }


       else{
       int opt= JOptionPane.showConfirmDialog(null,"Are you sure to SHARE this ? ");

        if(opt==0){
       

        stsid=""+id;


 Connection con;
        Statement stmt;
        ResultSet rs;


   try{

            Class.forName("java.sql.DriverManager");
 con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/facebook","root","");
 stmt=(Statement) con.createStatement();




  rs=stmt.executeQuery("select sysdate();");


        while(rs.next()){
           time=rs.getString("sysdate()");

}


stmt.executeUpdate("insert into status values('"+sts+"','"+stsid+"','"+time+"');");
 statusarea.setText("");


         }
catch(Exception e){
JOptionPane.showConfirmDialog(null, e.getMessage());

}






        }
       



       }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed


        int opt=JOptionPane.showConfirmDialog(null, "Are you sure to Log Out ?");
        if(opt==0){

 user=""; password=""; id="";pwrd="";fname=""; one=1;
profileframe.setVisible(false);
t1.setText("");
t2.setText("");
      }



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void delchatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delchatActionPerformed
 String listid=(String)chatList.getSelectedValue();
        Connection cn;
        Statement stmt;
        ResultSet rs;
        try{

            Class.forName("java.sql.DriverManager");
            cn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/facebook","root","");
            stmt=(Statement)cn.createStatement();
            stmt.executeUpdate("delete from chat where id_to='"+id+"' and id_from='"+listid+"';");
            stmt.executeUpdate("delete from chat where id_to='"+listid+"' and id_from='"+id+"';");

        chatbox.setText("");
        chatline.setText("");


        ok=0;
        chatbut.doClick();




        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }



        // TODO add your handling code here:
}//GEN-LAST:event_delchatActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
 try{
    Class.forName("java.sql.DriverManager");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/","root","");
            Statement stmt=con.createStatement();
            String query="Create database facebook;";
                    stmt.executeUpdate(query);
                    query="use facebook;";
                    stmt.executeUpdate(query);
query="Create table profile(id char(50) primary key,pwrd char(50),fname char(50),lname char(50),dob date);";
stmt.executeUpdate(query);
      query= "Create table status(sts text,id char(50),time char(50));";stmt.executeUpdate(query);
       query= "Create table chat(id_to char(50),id_from char(50),chat text);";stmt.executeUpdate(query);

          JOptionPane.showMessageDialog(null, "Database created Successfully. :D ");
           
          
            
}
    catch(Exception e){
    JOptionPane.showConfirmDialog(null, e.getMessage());
    }    
 // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed


  




    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facebook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb;
    private javax.swing.JList chatList;
    private javax.swing.JTextArea chatbox;
    private javax.swing.JButton chatbut;
    private javax.swing.JLabel chatlabel;
    private javax.swing.JTextArea chatline;
    private javax.swing.JButton chatlist;
    private javax.swing.JButton delchat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton jb;
    private javax.swing.JButton jb2;
    private javax.swing.JComboBox jcb1;
    private javax.swing.JComboBox jcb2;
    private javax.swing.JComboBox jcb3;
    private javax.swing.JDialog jd1;
    private javax.swing.JDialog jd2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JFrame profileframe;
    private javax.swing.JLabel propic;
    private javax.swing.JTextArea statusarea;
    private javax.swing.JTextArea stsa1;
    private javax.swing.JTextArea stsa2;
    private javax.swing.JTextArea stsa3;
    private javax.swing.JLabel stsl1;
    private javax.swing.JLabel stsl2;
    private javax.swing.JLabel stsl3;
    private javax.swing.JTextField t1;
    private javax.swing.JPasswordField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JPasswordField t6;
    private javax.swing.JTextField t7;
    // End of variables declaration//GEN-END:variables

}
